apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: browserless
  name: browserless
  namespace: changedetect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless
  template:
    metadata:
      labels:
        app: browserless
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: browserless-configs
          image: ghcr.io/browserless/chrome:v2.25.2
          name: browserless
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 1G
            limits:
              cpu: 1000m
              memory: 1G
      restartPolicy: Always
