apiVersion: v1
kind: PersistentVolume
metadata:
  name: changedetectionio-data
spec:
  capacity:
    storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: caminho_nfs/pv-changedetectionio
    server: 192.168.0.x