apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-changedetectionio-data
  namespace: testns
spec:
  resources:
    requests:
      storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: changedetectionio-data
